// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbabSoSgfOAGLVQpbXU7B90IGiXbv01ZA',
    appId: '1:1075629088067:web:7621476a8ea9e04dc6e3f6',
    messagingSenderId: '1075629088067',
    projectId: 'chat-researchteam',
    authDomain: 'chat-researchteam.firebaseapp.com',
    storageBucket: 'chat-researchteam.appspot.com',
    measurementId: 'G-SXKN2EXT6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFm6Un1iQ6-_MgHchodBTeqCCxYxJYLWs',
    appId: '1:1075629088067:android:11f972ecfd5d55dec6e3f6',
    messagingSenderId: '1075629088067',
    projectId: 'chat-researchteam',
    storageBucket: 'chat-researchteam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAo2ioUYTlruqxP2JRiuHpbSGh03G2KXg',
    appId: '1:1075629088067:ios:4b2200082623a871c6e3f6',
    messagingSenderId: '1075629088067',
    projectId: 'chat-researchteam',
    storageBucket: 'chat-researchteam.appspot.com',
    iosClientId: '1075629088067-fganrc9b2sg2acoee0apgqkohkfelir9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myreapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAo2ioUYTlruqxP2JRiuHpbSGh03G2KXg',
    appId: '1:1075629088067:ios:4b2200082623a871c6e3f6',
    messagingSenderId: '1075629088067',
    projectId: 'chat-researchteam',
    storageBucket: 'chat-researchteam.appspot.com',
    iosClientId: '1075629088067-fganrc9b2sg2acoee0apgqkohkfelir9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myreapp',
  );
}
